NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc
    
api_parkings:
    type: rest
    resource: ApiBundle:Parkings

api_parking_slot_service:
    type: rest
    resource: ApiBundle:ParkingSlots