services: 

    blackout_service:
        class: AppBundle\Service\ParkingService
        arguments: [ "@service_container" ]

    command_listener:
        class: AppBundle\Listener\CommandListener
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_listener, event: console.command }
